config/routes.rb
Rails.application.routes.draw do
  
  get 'pricing', to: 'static_pages#pricing'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def pricing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ciapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <div class="flex flex-col">
        <%= link_to 'Home', root_path %>
        <%= link_to 'Pricing', pricing_path %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/static_pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">StaticPages#home</h1>
  <p>Find me in app/views/static_pages/home.html.erb</p>
</div>

app/views/static_pages/pricing.html.erb
<div>
  <h1 class="font-bold text-4xl">StaticPages#pricing</h1>
  <p>Find me in app/views/static_pages/pricing.html.erb</p>
</div>